"""Add Category model and link to TransactionItem

Revision ID: 3084443faab9
Revises: 6ffa6f479010
Create Date: 2025-07-05 13:15:17.063263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3084443faab9'
down_revision = '6ffa6f479010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True, comment='費用分類ID'))
        batch_op.create_foreign_key(batch_op.f('fk_transaction_items_category_id_categories'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_items_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')

    # ### end Alembic commands ###
