"""Add cash count session and detail models

Revision ID: bf24db95b8f2
Revises: d239f394d13b
Create Date: 2025-07-04 13:10:52.954011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf24db95b8f2'
down_revision = 'd239f394d13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_count_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_date', sa.DateTime(), nullable=False, comment='盤點日期'),
    sa.Column('counted_total', sa.Numeric(precision=10, scale=2), nullable=False, comment='盤點總額'),
    sa.Column('system_balance', sa.Numeric(precision=10, scale=2), nullable=False, comment='系統帳上餘額'),
    sa.Column('difference', sa.Numeric(precision=10, scale=2), nullable=False, comment='差額'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作人員ID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_count_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denomination', sa.Integer(), nullable=False, comment='面額 (例如: 1000, 500)'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='張數/個數'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='該面額小計'),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['cash_count_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_count_details')
    op.drop_table('cash_count_sessions')
    # ### end Alembic commands ###
